# Project information
site_name: JoyHome HowTo
site_description: Clear Wonderings About Your Dream Home and Investment
repo_name: GitHub  #valid value 'GitHub', 'BitBucket', 'GitLab'
repo_url: 'https://github.com/ericcma/JoyHomeHowTo/'
site_url: https://github.com/ericcma/JoyHomeHowTo/
site_author: Eric Ma
#extra:
#  repo_icon: github
#Copyright
copyright: 'Copyright &copy; 2019 JoyHome Maintained by Eric Ma'

#Theme
#'material','windmill' ,cinder,mkdocs,readthedocs, rtd-dropdown
theme: 
#  dir: 'theme'
  name: 'material'   
  palette:
    primary: 'teal'
    accent: 'teal'
  font:
    text: 'Open Sans'
    code: 'Source Sans Pro'
  logo: 
    icon: 'whatshot'
  favicon: 'assets/images/logo.png'
  repo_icon: gitlab
  feature:
    tabs: true
  custom_dir: 'theme'

markdown_extensions:
  - admonition:                      #block style content
  - codehilite:                       #language highter
      guess_lang: false
  - pymdownx.arithmatex:
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret:
  - pymdownx.critic:
  - pymdownx.details:
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.inlinehilite:
  - pymdownx.magiclink:
  - pymdownx.mark:
  - pymdownx.smartsymbols:
  - pymdownx.superfences:
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde:
  - toc:
      permalink: true
      baselevel: 1
      toc_depth: 3
  - extra:              #enable markdown within div   
  - attr_list:          #give rendered html attribute such as Id
  - markdown_include.include:
      base_path: docs
      
#plugins:
#    - pdf-export:
    
#Extra    
extra_css:
  - 'css/extra.css'
  
extra_javascript:
  - 'js/extra.js'
  
extra:
  social:
    - type: 'github'
      link: 'https://ericcma.github.io/'
    - type: 'twitter'
      link: 'https://ericcma.github.io/'

edit_uri: 'tree/master/project-documents/docs/'
#Navigations      
nav:
    - General:
        - Contact: 'index.md'

        - Buyer:
            - 购买居住房要考虑的因素: 'realestate/buyer/principle-buy-primary-home.md'
            - 购买居住房程序: 'realestate/buyer/house-purchase-steps.md'
            - 房屋常见问题: 'realestate/all-love/02_residential_house_flaws.md'
            - 关于房屋朝向: 'realestate/buyer/pinciple-house-orientation.md'
            - 房屋贷款原则: 'realestate/buyer/mortage-shopping-principle.md'
            - 房屋贷款步骤: 'realestate/buyer/mortgage-steps.md'
            - 楼花及购买步骤: 'realestate/buyer/new-construction.md'

        - Seller:
            - Principles of sellinging a primary house: 'realestate/seller/principle-sell-primary-home.md'
        - Landlord-Renter:
            - General Info: 'realestate/landlord-renter/general/01_general-info.md'
            - Landlord: 'realestate/landlord-renter/landlord/01_forms.md'
            - Renter: 'realestate/landlord-renter/renter/01_forms.md'
    - Projects:
        - Orlando Vacation Homes:
            - Why ?: 'realestate/projecs/orlando/01-why.md'
            - What ?: 'realestate/projecs/orlando/02-what.md'
            - How ?: 'realestate/projecs/orlando/03-how-it-work.md'
            - Mortgage: 'realestate/projecs/orlando/04-get-financialized.md'
            - ROI Analysis - 1: 'realestate/projecs/orlando/05-roi-1.md'
            - ROI Analysis - 2: 'realestate/projecs/orlando/06-roi-2.md'
            - ROI Analysis - 3: 'realestate/projecs/orlando/07-roi-3.md'
            - 'Question & Answer': 'realestate/projecs/orlando/08-qa.md'

    - Agent:
        - Transaction Management:
            - Commission Rebate: 'realestate/agent/transaction-management/01_commission_rebate.md'
            - Disclosure of Interests: realestate/agent/transaction-management/02_disclosure_of_interest.md
            - Offer Examples: realestate/agent/transaction-management/03_offer_examples.md
            - Webform Templates: realestate/agent/transaction-management/04_webform_emplate.md
            - Document Needs for Transactions:
                - Listing:
                    - Resale: realestate/agent/transaction-management/05_document_needs_for_transactions/transaction_listing_resale.md
                    - Lease: realestate/agent/transaction-management/05_document_needs_for_transactions/transaction_listing_lease.md
                    - Assignment: realestate/agent/transaction-management/05_document_needs_for_transactions/transaction_listing_assignment.md
                - Co-Operate:
                    - Resale: realestate/agent/transaction-management/05_document_needs_for_transactions/transaction_coop_resale.md
                    - Lease: realestate/agent/transaction-management/05_document_needs_for_transactions/transaction_coop_lease.md
                    - Assignment: realestate/agent/transaction-management/05_document_needs_for_transactions/transaction_coop_assignment.md
                - 'New Construction': 'realestate/agent/transaction-management/05_document_needs_for_transactions/transaction_new_construction.md'
            - Schefule B: realestate/agent/transaction-management/06_scheduleB.md
            - Transaction Summary: realestate/agent/transaction-management/07_transaction_summary.md
            - Fintrac Forms: realestate/agent/transaction-management/08_fintrac_forms.md
        - Training:
            - Fill Web Forms Step-By-Step Vedios: 'realestate/agent/training/bsg-realestate-step-by-step.md'
        - Case Resolution:
            - Apply Deposit To New Agreement: 'realestate/agent/case-resolution/case-resolution-01.md'
    - TechGuide:
        #- 'Git Guide': 'setup-env/git-guide.md'
        - 'Markdown Language Syntax': 'setup-env/markdownsyntax.md'
        - 'MkDocs Guide': 'setup-env/mkdocs-guide.md'