# Project information
site_name: JoyHome HowTo
site_description: Wonderings about your dream home and investment
repo_name: GitHub  #valid value 'GitHub', 'BitBucket', 'GitLab'
#repo_name: 'CorHealth-Report Docs'
repo_url: 'https://github.com/ericcma/JoyHomeHowTo/'
site_url: http://localhost:8000/
site_author: Eric Ma
#extra:
#  repo_icon: github
#Copyright
copyright: 'Copyright &copy; 2018 JoyHome'

#Theme
#'material','windmill' ,cinder,mkdocs,readthedocs, rtd-dropdown
theme: 
#  dir: 'theme'
  name: 'material'   
  palette:
    primary: 'teal'
    accent: 'teal'
  font:
    text: 'Open Sans'
    code: 'Source Sans Pro'
  logo: 
    icon: 'whatshot'
  favicon: 'assets/images/logo.png'
  repo_icon: gitlab
  feature:
    tabs: true
  custom_dir: 'theme'

markdown_extensions:
  - admonition:                      #block style content
  - codehilite:                       #language highter
      guess_lang: false
  - pymdownx.arithmatex:
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret:
  - pymdownx.critic:
  - pymdownx.details:
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.inlinehilite:
  - pymdownx.magiclink:
  - pymdownx.mark:
  - pymdownx.smartsymbols:
  - pymdownx.superfences:
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde:
  - toc:
      permalink: true
      baselevel: 1
      toc_depth: 3
  - extra:              #enable markdown within div   
  - attr_list:          #give rendered html attribute such as Id
  - markdown_include.include:
      base_path: docs
      
#plugins:
#    - pdf-export:
    
#Extra    
extra_css:
  - 'css/extra.css'
  
extra_javascript:
  - 'js/extra.js'
  
extra:
  social:
    - type: 'github'
      link: 'https://ericcma.github.io/'
    - type: 'twitter'
      link: 'https://ericcma.github.io/'

edit_uri: 'tree/master/project-documents/docs/'
#Navigations      
nav:
    - 'Technic-Guide':
        - 'Introduction': index.md
        - 'Git Guide': 'setup-env/git-guide.md'
        - 'MkDocs Guide': 'setup-env/mkdocs-guide.md'
    - Buyer-Seller:
        - General Info:
            - 房屋常见问题: 'realestate/buyer-seller/general/02_residential_house_flaws.md'
        - Buyer:
            - 购买居住房的基本原则: 'realestate/buyer-seller/buyer/principle-buy-primary-home.md'
            - 购买居住房的基本步骤: 'realestate/buyer-seller/buyer/house-purchase-steps.md'
            - 楼花及购买步骤： 'realestate/buyer-seller/buyer/new-construction.md''
            - 贷款基本步骤: 'realestate/buyer-seller/buyer/mortgage-steps.md'
            - 如何选择房屋的朝向: 'realestate/buyer-seller/buyer/pinciple-house-orientation.md'
        - Seller:
            - Principles of sellinging a primary house: 'realestate/buyer-seller/seller/principle-sell-primary-home.md'
    - Landlord-Renter:
        - General Info: 'realestate/landlord-renter/general/01_general-info.md'
        - Landlord: 'realestate/landlord-renter/landlord/01_forms.md'
        - Renter: 'realestate/landlord-renter/renter/01_forms.md'
    - Agent:
        - Transaction Management:
            - Commission Rebate: 'realestate/agent/transaction-management/01_commission_rebate.md'
            - Disclosure of Interests: realestate/agent/transaction-management/02_disclosure_of_interest.md
            - Offer Examples: realestate/agent/transaction-management/03_offer_examples.md
            - Webform Templates: realestate/agent/transaction-management/04_webform_emplate.md
            - Document Needs for Transactions:
                - Listing:
                    - Resale: realestate/agent/transaction-management/05_document_needs_for_transactions/transaction_listing_resale.md
                    - Lease: realestate/agent/transaction-management/05_document_needs_for_transactions/transaction_listing_lease.md
                    - Assignment: realestate/agent/transaction-management/05_document_needs_for_transactions/transaction_listing_assignment.md
                - Co-Operate:
                    - Resale: realestate/agent/transaction-management/05_document_needs_for_transactions/transaction_coop_resale.md
                    - Lease: realestate/agent/transaction-management/05_document_needs_for_transactions/transaction_coop_lease.md
                    - Assignment: realestate/agent/transaction-management/05_document_needs_for_transactions/transaction_coop_assignment.md
                - 'New Construction': 'realestate/agent/transaction-management/05_document_needs_for_transactions/transaction_new_construction.md'
            - Schefule B: realestate/agent/transaction-management/06_scheduleB.md
            - Transaction Summary: realestate/agent/transaction-management/07_transaction_summary.md
            - Fintrac Forms: realestate/agent/transaction-management/08_fintrac_forms.md
        - Training:
            - Fill Web Forms Step-By-Step Vedios: 'realestate/agent/training/bsg-realestate-step-by-step.md'
        - Case Resolution:
            - Apply Deposit To New Agreement: 'realestate/agent/case-resolution/case-resolution-01.md'